name: savery
description: Aplikasi pencatatan keuangan pribadi - Savery
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.3
  path: ^1.9.0

  # State management
  provider: ^6.1.2

  # Charts
  fl_chart: ^0.69.0

  # UI
  google_fonts: ^6.2.1

  # Image picker & OCR
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  path_provider: ^2.1.4
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  remove_alpha_ios: true
